### ISSUE TITLE
Maximizing window with windows shortcut broken

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1576]
### Short Summary
When I open a new Komodo window, I always maximize the window using the windows shortcut:
win + arrow up

Only this is not working in Komodo X, I have to click the maximize button manual.

### Steps to Reproduce
Open a new Komodo window and try to maximize it wit win + arrow up

### Expected results
The window gets maximized

### Actual results
Nothing Happen

**Comment by mitchell-as** [comment]
@cgchoffman can you reproduce this?

**Comment by babobski** [comment]
Tested it on work, but it's working fine here. The only difference is that at home i started with a new profile and at work I have all my settings copied over also my keybindings. Only here it's working as expected.

Will test it some more when I'm back at home.

**Comment by Naatan** [comment]
Do you use the same OS both at work and at home?

Could you try seeing if using "Native Window Decorations" (Prefs > Appearance) resolves the issue?

**Comment by cgchoffman** [comment]
This was fixed quite a while ago.  Make sure you're not using a beta release @babobski.  I just double checked and it's working fine for me.  I've reset my profile as well and I can still manipulate the window as expect by using *win + up/right/down/left*.  *Native Window Decorations* are **off**

**Comment by babobski** [comment]
I have te same Os on both, they are both windows 10 and got almost the same specification.
Native Window Decorations fixed the problem, the only thing i noticed that the the full screen and minimized window where the same height. When i now turn off Native Window Decorations the shortcut is still working.

When i reboot komodo the shortcuts are still working, only the minimized window has grown again to the same size as the full screen mode. ( i resized it in the last session because it was so large ).

A other thing i noticed is when i use <kbd>win + left arrow</kbd> or right, the application is not resizing to the correct width, it should be 50% of the screen, but is resizing to around 80% - 90%
![2016-05-24 20_23_38](https://cloud.githubusercontent.com/assets/3530262/15515270/998327f6-21ed-11e6-8e3b-90b0477175f0.png)

The build I'm using here:
Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016. (build on my birthday :))

**Comment by Naatan** [comment]
Does pressing win + left repeatedly resize it to 50%?

**Comment by babobski** [comment]
@Naatan Tested this, at home I have one monitor, when i press win + left repeatedly, the komodo screen moves from the left side to the right side of the screen and visa versa. Its getting smaller but still not smaller as 60%.

At work I have tree monitors, it first resizes to 80-90%, If I then press win + less the window moves to the other screen without resizing. If I now press win + left arrow the window get minimized.
If I then press win + left key the window is resizing to 50% of the screen.

If I first minimize the window wit win + down key and then press the win + left key the window is resized to 50%

**Comment by cgchoffman** [comment]
I'm not noticing Komodo move any differently than other applications on my computer.  I do notice that Komodo (and other applications) will take up more than  50% on my vertical monitor but that seems normal to me, it's too narrow and Komodo likely has a min width that you wouldn't want to go below any way.

There is other oddities i've noticed with Windows 10 Win + Arrow actions.  It's more robust and allows you to adjust windows in different ways now.  I don't find that Komodo does anything differently from other applications.  Maybe it's the new Windows key actions your noticing @babobski ?

**Comment by babobski** [comment]
@cgchoffman Komodo is the only application who not behaves the same as the rest of the applications.
With other applications, when I press `win + left key` the applications becomes 50% of my screen, on the other half it will show my other open applications. When i click on one of them, this will fill up the other half screen so i have a split view:
![2016-05-26 08_47_50](https://cloud.githubusercontent.com/assets/3530262/15565984/a3ab1fb8-231e-11e6-9d57-3a561f530ffc.jpg)
When i do the same with Komodo i get this result:
![2016-05-26 08_49_10](https://cloud.githubusercontent.com/assets/3530262/15566008/cea9c638-231e-11e6-8a92-a5b1be3d999f.jpg)
This is incorrect, I should get a splitted view (50% / 50%)
The new function in Windows 10 is that i can split it horizontal to, so I can get 4 applications on 1 screen (as can bee seen in this [video](https://www.youtube.com/watch?v=lQEEQQeQsGA) )
![2016-05-26 08_56_24](https://cloud.githubusercontent.com/assets/3530262/15566221/e87bbfe8-231f-11e6-99fa-f25c5cd1adce.jpg)

If I try to get Komodo in splitted view It will not work, the second screen will overlay the first one:
![2016-05-26 08_59_49](https://cloud.githubusercontent.com/assets/3530262/15566283/3d8cedfe-2320-11e6-9879-c42e7bd383fe.jpg)

**Comment by Naatan** [comment]
I think I know the issue. Try hiding your toolbar, if the issue is what I think it is it will resize properly with the toolbar hidden.

**Comment by babobski** [comment]
@Naatan tested it but it works correct when I hide the toolbar and have the bottom sidepane closed:
![2016-05-26 17_51_24](https://cloud.githubusercontent.com/assets/3530262/15580877/89c24b8e-236a-11e6-8225-ef0ccd6cc5b0.png)
If the bottom side pane is open the height is going wrrong:
![2016-05-26 17_56_05](https://cloud.githubusercontent.com/assets/3530262/15581042/2a5de5a8-236b-11e6-9734-a04942469dea.png)

Also when i disable the toolbar and I'm in the maximized window, the top of the window get's cut of:
![2016-05-26 17_58_42](https://cloud.githubusercontent.com/assets/3530262/15581214/b4245402-236b-11e6-98b3-351c6ec5f1ae.png)

**Comment by Naatan** [comment]
Thanks @babobski, that confirms my suspicions. 

We have a bug open for the maximized window issue.

**Comment by tonyattwood** [comment]
Hi,

I wanted  to ask you if you know  anything about  that stuff? If that's  happening now, what's gonna be next? Take a  look <http://excellent.leekongwah.com/e4mtjqr>

Be well, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
Hey,

I think this app is gonna be helpful for you, read more  here <http://enjoy.recentlysoldhomes.info/e4tfygot>

Be well, tony.attwood@ntlworld.com
