### ISSUE TITLE
Komodo docs support page is very outdated

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1882]
### Short Summary

http://docs.komodoide.com/Manual/support

Bug reporting links are wrong.  Mailing lists are being phased out.  Feedback email isn't really used.  etc.

**Comment by Defman21** [comment]
Fixed links for filing bugs.

**Comment by Naatan** [comment]
Fixed rest. Thanks @Defman21. @cgchoffman note you have editing rights ;)

**Comment by Defman21** [comment]
I just didn't know your mailing lists and stuff :P

**Comment by cgchoffman** [comment]
> @cgchoffman note you have editing rights ;)

and other stuff to spend time on :P

**Comment by Defman21** [comment]
@Naatan you forgot to update Feature Requests section. I've done that.
