### ISSUE TITLE
Files not opening

### ISSUE THREAD

**Issue by bbusschots-mu** [Komodo/KomodoEdit#217]
After upgrading to Komodo Edit 9 everything was fine for a few hours, but then I began to have problems opening files. Some files just refuse to open. When I double-click them, they don't open. When I right-click them and choose Open, they don't open. When I click the Open File button on the home page and browse to them, they do not open.

There is no error message given, the command to open the files simply seems to be ignored!

This bug is so bad it has made the app un-usable. What good is a text editor that can't open text files?!

**Comment by Naatan** [comment]
Does restarting Komodo resolve the issue (temporarily)?

Could you post your error log after reproducing the issue (pystderr.log - https://community.activestate.com/faq/komodo-profile-structure)?

> What good is a text editor that can't open text files?!

Obviously this is not by design .... ;)

**Comment by bbusschots-nuim** [comment]
Hi Nathan,

Attached is the requested error log.

If there's any other info I can give you to help track down this bug just ask.

Regards,

Bart.



--
Bart Busschots
Systems Programmer
Maynooth University Computer Centre




Maynooth University, Maynooth, Co. Kildare, Ireland

T: +353 1 708 3830
E: bart.busschots@nuim.ie
W: www.maynoothuniversity.ie

**Comment by Naatan** [comment]
Unfortunately github does not seem to process attachments. 

Note the error log resets each time you start Komodo, so unless you have a log from a Komodo session where the actually issue occurred it will not be of much help regarding this bug.

**Comment by bbusschots-nuim** [comment]
[2015-04-27 17:20:15,841] [INFO] Startup: Welcome to Komodo Edit 9.0.1 build 15745 (platform macosx, running on Darwin 14.3.0 version Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64)
[2015-04-27 17:20:16,016] [INFO] Startup: /Applications/Komodo Edit 9.app/Contents/MacOS/komodo built on Mon Apr 20 17:19:25 2015
[2015-04-27 17:20:28,739] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2015-04-27 17:21:39,058] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-04-27 17:21:39,059] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-04-27 17:21:39,060] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-04-27 17:21:39,060] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-04-27 17:21:42,534] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-04-27 17:21:50,094] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2324
[2015-04-27 17:21:50,996] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2324
[2015-04-27 17:22:11,884] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-04-27 17:22:11,885] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-04-27 17:22:44,853] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-04-27 17:22:52,283] [WARNING] keybindings: [Meta+Shift+Down] was used for 'cmd_selectDocumentHome', overriding to use 'cmd_selectDocumentEnd'
[2015-04-27 17:23:03,255] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-04-27 17:23:03,256] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-04-27 17:23:03,256] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-04-27 17:23:03,256] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-04-27 17:23:03,257] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-04-27 17:23:03,257] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-04-27 17:23:03,257] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-04-27 17:23:27,599] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-04-27 17:23:27,938] [DEBUG] places_js: waiting for document complete
[2015-04-27 17:23:34,165] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-04-27 17:23:34,165] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-04-27 17:23:34,165] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-04-27 17:23:34,165] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-04-27 17:23:34,166] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-04-27 17:23:34,166] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-04-27 17:23:34,167] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-04-27 17:24:00,163] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/components/koamAddonManager.js:138
ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 217, in initWithFile
    self._setupPrefs()
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 320, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 281, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocumentService.py", line 245, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocumentService.py", line 230, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-04-27 17:24:33,585] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:570
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 570, in 

ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 217, in initWithFile
    self._setupPrefs()
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 320, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocument.py", line 281, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocumentService.py", line 245, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "/Applications/Komodo Edit 9.app/Contents/Resources/components/koDocumentService.py", line 230, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-04-27 17:25:15,801] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:570
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 570, in 

[2015-04-27 17:27:12,443] [WARNING] views: Inconsistent view count in view_closed event
[2015-04-27 17:27:13,482] [ERROR] commands: doing _updateCommand: cmd_findInPlace: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 125}]'[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 125}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeControlle'...291 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 105
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 105
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset :: line 125
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:105:22
command_updateCommandset@c'...1292 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-04-27 17:27:13,483] [ERROR] commands: doing _updateCommand: cmd_replaceInPlace: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 137}]'[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 137}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeControlle'...291 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 105
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 105
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset :: line 125
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:105:22
command_updateCommandset@c'...1292 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-04-27 17:27:13,496] [ERROR] commands: doing _updateCommand: cmd_places_showInFinder: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 149}]'[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 149}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeControlle'...291 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 105
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 105
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset :: line 125
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:105:22
command_updateCommandset@c'...1292 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-04-27 17:27:13,498] [ERROR] commands: doing _updateCommand: cmd_places_goUpOneFolder: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 231}]'[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeController.js" line: 231}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is null" {file: "chrome://komodo-places/content/placeControlle'...291 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 105
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 105
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 105
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset :: line 125
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:105:22
command_updateCommandset@c'...1292 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-04-27 17:27:15,642] [ERROR] console-logger: TypeError: ko.places.manager is null (2) in chrome://komodo-places/content/placeController.js:125
Traceback (most recent call last):
  File "chrome://komodo-places/content/placeController.js", line 125, in 

[2015-04-27 17:27:15,712] [ERROR] console-logger: TypeError: ko.places.manager is null (2) in chrome://komodo-places/content/placeController.js:137
Traceback (most recent call last):
  File "chrome://komodo-places/content/placeController.js", line 137, in 

[2015-04-27 17:27:15,713] [ERROR] console-logger: TypeError: ko.places.manager is null (2) in chrome://komodo-places/content/placeController.js:149
Traceback (most recent call last):
  File "chrome://komodo-places/content/placeController.js", line 149, in 

[2015-04-27 17:27:15,714] [ERROR] console-logger: TypeError: ko.places.manager is null (2) in chrome://komodo-places/content/placeController.js:231
Traceback (most recent call last):
  File "chrome://komodo-places/content/placeController.js", line 231, in

**Comment by Naatan** [comment]
Hmm, could you try installing the [developer extension](http://komodoide.com/resources/addons/komodo--komododeveloperextension/), then restart Komodo. Now hit Tools > Extension Developer > Javascript Shell. In the dialog that pops up enter:

```
ko.prefs.getString('encodingDefault')
```

What does that give you?

**Comment by bbusschots-nuim** [comment]
Hi Nathan,

The output from the requested command is:

mac-roman

Regards,

Bart.

--
Bart Busschots
Systems Programmer
Maynooth University Computer Centre




Maynooth University, Maynooth, Co. Kildare, Ireland

T: +353 1 708 3830
E: bart.busschots@nuim.ie
W: www.maynoothuniversity.ie

**Comment by parkedr** [comment]
I'm having the same problems - not matter how I try to open some files, nothing happens. The output of the developer extension command is: cp1252. I'll attach my log in a separate post.

**Comment by parkedr** [comment]
[2015-05-05 10:49:48,055] [INFO] Startup: Welcome to Komodo IDE 9.0.1 build 87208 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-05-05 10:49:48,055] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Thu Apr 16 11:54:31 2015
[2015-05-05 10:49:49,665] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-05-05 10:49:49,667] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-05-05 10:49:49,667] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-05-05 10:49:49,668] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-05-05 10:49:49,668] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///C:/Users/rparker/AppData/Local/ActiveState/KomodoIDE/9.0/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///C:/Users/rparker/AppData/Local/ActiveState/KomodoIDE/9.0/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2015-05-05 10:49:50,023] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-05-05 10:49:50,424] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-05-05 10:49:50,424] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:20
[2015-05-05 10:49:51,562] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2015-05-05 10:49:51,640] [WARNING] keybindings: [Ctrl+Shift+U] was used for 'cmd_convertLowerCase', overriding to use 'cmd_scope-sections'
[2015-05-05 10:49:53,188] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-05-05 10:49:53,694] [DEBUG] places_js: waiting for document complete
[2015-05-05 10:49:53,752] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koDocument.py", line 184, in initWithFile
    self._setupPrefs()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koDocument.py", line 287, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koDocument.py", line 248, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koDocumentService.py", line 212, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koDocumentService.py", line 197, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-05-05 10:50:38,109] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:537
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 537, in 

[2015-05-05 10:54:26,397] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-05-05 10:54:26,397] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-05-05 10:54:26,398] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by bbusschots-nuim** [comment]
An update on this - the problem was not fixed with the 9.1 update, and it seems to be triggered by opening old project files.

I was working away in KE9.1 all afternoon yesterday on new projects, and there were no problems. Then, this morning I closed the project I had been working on and opened an old project, and from that moment on KomodoEdit lost the ability to open any files. I had to change back to KE8 to get any work done.

I'm also disappointed that there appears to be no progress at all on this catastrophic bug. I would have thought that a text editor's inability to open text files would be a top-priority bug.

**Comment by cgchoffman** [comment]
You are correct bart, i've raise prio and set a milestone on this issue.  That didn't happen so it slipped through the cracks.

**Comment by Naatan** [comment]
Unfortunately this bug should not have been targeted for a milestone to begin with, least not until we have managed to reproduce it (hard to fix otherwise).

Could you test if a clean profile solves the issue? https://community.activestate.com/node/15233

**Comment by bbusschots-nuim** [comment]
This issue does not seem to exist when running under a clean profile. I opened a few old projects, and about 10 files in each, and all files opened as expected.

**Comment by Naatan** [comment]
Thanks, could you try deleting the doc-state.xmlc and view-state.xmlc from your Profile folder (while Komodo is not running)?

If that does not work, could you send me your prefs.xml? You can email me this directly if you are concerned about sensitive data: nathanr at activestate dot com

**Comment by bbusschots-nuim** [comment]
Deleting those two files seems to have done the trick.

**Comment by Naatan** [comment]
Thanks, I've committed an experimental fix for the issue, since I cannot reproduce the problem I cannot verify whether this fix solves the issue.

**Comment by monolied** [comment]
I had the same issue starting Komodo Edit 9.2 under Windows 7. I renamed doc-state.xmlc and the issue disappeared. (I had configurations dating back to 6.2 in that dir and doc-state.xmlc was 24kb. The newly created doc-state.xmlc has 2kb.)
If you're interested I could post the corrupt (?) doc-state.xmlc somewhere.

**Comment by Naatan** [comment]
A copy of your (or anyone who is experiencing this issue) doc-state.xmlc would be very much appreciated.

You can find your doc-state.xmlc here: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

**Comment by rjasdf** [comment]
It's a year later and 10.1, but the collab_remote_cursor warnings still exist.  What are they about?

**Comment by cgchoffman** [comment]
@rjasdf I believe that is related to using an unsupported scheme.  Try changing your scheme in Edit > Preferences > Color Scheme.

Note: This ticket is not related to that warning at all.

I think this ticket is obsolete now that we've reach Komodo 10.
