### ISSUE TITLE
adding a quote removes the next quote in editor

### ISSUE THREAD

**Issue by NinsgVeen** [Komodo/KomodoEdit#2447]
When typing a quote (single or double) the quote that follows gets removed. Even when that quote is on another line and/or in another element.

#### Steps to Reproduce
I found this problem when editing HTML (tpl) or JS files.
I opened a HTML file and added a new element by typing it myself (no copy or use of auto insert) somewhere in the beginning of the body. I usually type both double quotes first, before going back a position and typing the classname. This element has a class and therefore double quotes in this case:
`<div class="new-element"></div>`
I found that when typing a quote, Komodo automatically selects the following quote, making you replace the quote with text if you type 1 quote first, then classname and then the last quote. Also not a desired outcome.

#### Expected results
I expect to be able to add this element without changing the rest of document. 
Total expected code:
`<div class="new-element"></div><div class="existing-element"></div>`

#### Actual results
The element that follows after the new element, which already existed changes from:
`<div class="existing-element"></div>` 
to:
`<div class=existing-element"></div>`
As you can see the first double quote has been removed. This will error when viewing the file in a browser and if you're not familiar with this problem it'll take a while to find...
Total actual code:
`<div class="new-element"></div><div class=existing-element"></div>`

#### Platform Information
I use Komodo Edit 10.2.1 with the sites plugin on MacOS Sierra 10.12
 
#### Extra Information
This problem started after updating to the latest version of komodo edit. It might be a conflict with keyboard settings, but I've been using Komodo 10 without this issue for at least half a year. Komodo 9 some years before that. Nevertheless, if it is a keyboard conflict: I use a wired apple keyboard with numpad. Let me know if I need different settings in either komodo or otherwise.

**Comment by mitchell-as** [comment]
Hi, I am not able to reproduce this problem, but that's probably because I do not understand your steps. I've tried the following in a brand new document:

1. Manually type `<div class=""`.
2. Press left arrow to go back into the quotes.
3. Manually type `existing-element`.
4. Press right arrow to go back out of the quotes.
5. Manually type `>`, at which point Komodo auto-inserts `</div>`.
6. Press Home to go to the beginning of the line (before `<div`).
7. Manually type `<div class=""`.
8. Press left arrow to go back inside the quotes.
9. Manually type `new-element`.
10. Press right arrow to go back outside the quotes.
11. Manually type `>`, at which point Komodo auto-inserts `</div>`.
12. I am left with the expected `<div class="new-element"></div><div class="existing-element"></div>` with no missing quotes.

Please advise where I'm going wrong.

**Comment by NinsgVeen** [comment]
Thank you for your quick response. 

Those steps are also my steps, so you haven't misunderstood. I've added a .mov screencapture file, perhaps it will help. 
[quote-bug.mov.zip](https://github.com/Komodo/KomodoEdit/files/899807/quote-bug.mov.zip)

It doesn't seem to happen when the entirety of the code is encased in quotes.
`"<div class='test-new'></div><div class='test-old'></div>"`
It also doesn't happen with new files that are yet to be defined and are therefore standard .txt files. 
In both cases auto-completion for the div doesn't happen here.

The files I've tried where remote, so I also tested a local file, same result.
I will try and fiddle with some file settings tomorrow.
Hopefully it's just me.

**Comment by Naatan** [comment]
Can'tt reproduce this either. However it looks related to a bug I fixed a few days ago, could you try the latest nightly?

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

If that doesn't work, see if the issue happens in safe-mode: `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by NinsgVeen** [comment]
You linked me the IDE, which I do not (yet) use. So I looked around and found the latest nightly for Edit:
[http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/](http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/)

Before installing I tried starting in safe mode for 10.2.1, no change.
I installed the latest nightly (10.2.2, build 17689) and tried safe mode, also no change.

After this I fiddled around with the settings for a bit and found that turning off 'Edit matching delimiter on select' in the 'Smart editing' tab fixed my issue.
It does select the next quote when I start typing the first quote, but when typing the second quote it won't remove the next one.
I believe the setting is for changing delimiters as well as closing delimiters (`<div></div>` f.e.) into another element (`<span></span>` f.e.), in one go. I have no problem with doing this manually. This happens less often than typing quotes anyway.

In my case the issue is fixed by not using this setting, hopefully when anyone else has this problem this works for them as well. Of course in the general sense this might still come up as an issue, but let's hope it was just me.

**Comment by Naatan** [comment]
Unfortunately disabling a setting is not a fix, but a workaround. You're saying that even when you disable that setting when you type a `"` it still selects the matching `"`? 

Very strange that you're able to reproduce this in safe-mode. Are you using any software that handles your keyboard input somehow?

**Comment by NinsgVeen** [comment]
I agree that in the general sense this doesn't fix the issue.

I use a mac with BTT/BetterTouchTool plugin. This handles some mice and window dragging functions, but it has capability for keyboard functions. I haven't entered any shortcuts so theoretically it shouldn't interfere. I saw there was an update for BTT(2.071) so I updated that and tested Komodo Edit in normal and safe mode again just in case, but enabling the checkbox gave me the same result/bug.
Disabling the app completely didn't affect the bug, meaning it was still there.

I have a macOS update ready, but I have that planned for this evening (6 hours from now)

I fiddled around again and thought there was a correlation between turning on and off the enable soft chars + inline and wrapping selection options but always leaving the edit matching elems off, but after testing again this was not the case. But perhaps you could try this as well.

**Comment by Naatan** [comment]
You might wanna hold off on updating OSX - https://github.com/Komodo/KomodoEdit/issues/2424. At least until they fix their update.

I'm gonna have a look at the logic for this and see if that might explain what you're seeing.

**Comment by NinsgVeen** [comment]
Unfortunately, when I received your message I already started the update. 

I will check out the other issue and see if this happens to me and if it does whether I can help with extra info.

Thank you for your assistance so far.

**Comment by Naatan** [comment]
I've tried to reproduce this issue in all 3 platforms under both edit and ide. I even went as far as to build edit off of master to see if that gave anything. No dice, I cannot reproduce this issue.

Are you still able to reproduce the issue now? I'm weighing more and more towards this being influenced by some external app/config.

**Comment by NinsgVeen** [comment]
I've been working with the OSX update for a day now and noticed no change. Thankfully I haven't experienced the problems like in issue #2424.

If no other users are experiencing my specific problem then, yes, I think it could be just me and a conflicting app. Haven't figured out what exactly, but if I do I'll let you know.

As I said before I've been able to work around it, so for me it's not a big issue.
