### ISSUE TITLE
Icons appear with numbers in boxes in IDE instead of as icons

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#2640]
### Short Summary

This is on behalf of Nathan Haynie:

The icons in the IDE do not appear as icons but as numbers/letters inside boxes instead. They used to appear before. This makes the IDE unusable. See images:
![image001](https://user-images.githubusercontent.com/17010135/26841486-7c1de77a-4a9e-11e7-9049-b1b3eaee3f1e.png)

Have tried the following to correct the problem but to no avail:

1)          Uninstall, reinstall.
2)          Uninstall, delete C:\Users\nhaynie2\AppData\Local\ActiveState, Reinstall
3)          Change the style to classic (as you see in the screenshot above)
4)          Restarting in "Safe Mode" did not help
5)          After doing "Reset Everything" (followed steps on web page)
                   - Did not correct problem
6)         After setting KOMODO_USERDATADIR=C:\temp
                   - Did not correct problem
7)         Altered the settings for the Windows Firewall as shown below:
                   - Did not correct problem
![image002](https://user-images.githubusercontent.com/17010135/26842603-48c5ef04-4aa2-11e7-9eba-018cee39dd89.png)

Also included the logs here:

[error.zip](https://github.com/Komodo/KomodoEdit/files/1055895/error.zip)

### Steps to Reproduce

No known steps as this just happened one day. It was working fine before. 

### Expected results

The icons should appear. 

### Actual results

They don't. 

### Platform Information

Komodo IDE 10.2.2 on Win 10. 

Note that this is a corporate machine and software updates are done regularly behind the 
scenes by the admins. The user has no control over what is updated.

The user's machine is only about 4 weeks old and Komodo IDE worked initially on it.  It is fully patched and gets the standard security/virus/malware treatment which the user is not privy to. He does not have issues with any other apps which include primarily:

-          Office 2016, Visio, Project, etc.
-          Visual Studio 2017
-          DB Visualizer
-          Putty
-          MySQL

Regarding GPU Acceleration: 
-          The closest thing he could find is Intel HD Graphics Control Panel but doesn’t see anything about graphics acceleration
-          In reviewing all the screens (only a few shown here) he doesn’t see an option to turn on/off acceleration
Please see ticket for screen snaps of his settings: 
https://otrs5.activestate.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=64340#212899

### Other Info

latest pystderr.log:
[2017-06-06 09:01:17,384] [INFO] Startup: Welcome to Komodo IDE 10.2.2 build 89895 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-06-06 09:01:17,384] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Fri Apr 28 17:11:08 2017
[2017-06-06 09:01:18,428] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-06-06 09:01:18,755] [ERROR] koProjectService: project_window_data:: getMostRecentWindow did not return a window
[2017-06-06 09:01:18,895] [ERROR] console-logger: downloadable font: not usable by platform (font-family: "icomoon" style:normal weight:normal stretch:normal src index:1)
source: chrome://komodo/skin/global/icons/fonts/icomoon.ttf?sc9q5w (0) in chrome://global/skin/global.css:1217
Traceback (most recent call last):
  File "chrome://global/skin/global.css", line 1217, in
 
[2017-06-06 09:01:19,724] [ERROR] koProjectService: project_window_data:: getMostRecentWindow did not return a window
[2017-06-06 09:01:19,844] [ERROR] koProjectService: project_window_data:: getMostRecentWindow did not return a window
[2017-06-06 09:01:20,369] [ERROR] console-logger: downloadable font: not usable by platform (font-family: "icomoon" style:normal weight:normal stretch:normal src index:2)
source: chrome://komodo/skin/global/icons/fonts/icomoon.woff?sc9q5w (0) in chrome://global/skin/global.css:1217
Traceback (most recent call last):
  File "chrome://global/skin/global.css", line 1217, in
 
[2017-06-06 09:01:20,384] [WARNING] console-logger: downloadable font: no supported format found (font-family: "icomoon" style:normal weight:normal stretch:normal src index:4)
source: (end of source list) (1) in chrome://global/skin/global.css:1217
[2017-06-06 09:01:20,551] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138

**Comment by i-shenl** [comment]
Also note that he's tried to do the following:

-  Deleted the C:\Users\nhaynie2\AppData\Local\ActiveState\KomodoIDE\10.2\XRE\icons directory
-  Started Komodo… icons still unavailable (see screenshot)
-  The \icons\ directory is back
-  Zipped \icons\ directory  and attached to this mail (see below)
-  Also attached log files (see error.zip above)

**Comment by cgchoffman** [comment]
This appears to be an issue in Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1228799#c28

In the linked comment the user appears to have found a workaround.

You can try the following in Komodo:
- open *View > Tabs & Sidebars > Console*
- paste and run the following into the *Console*: `ko.open.URI('about:config', 'browser');`
- search `gfx.direct2d.force-enabled`
- double click it to change it to TRUE
- close Komodo
- open Komodo

**Comment by nhtmo** [comment]
The above workaround did not work.  Steps taken:
1. Set gfx.direct2d.force-enabled (per instructions above)
2. Restart Komodo.  Icon issue not resolved.
3. Restart Windows 10, start Komodo.  Issue still persists.

Observations:
1. Per Jonathan Kew: "...while the problem is annoying, it's not all that widespread (only applies to specific flawed fonts, and only affects users on non-accelerated Windows)..."
2. Also per the same thread:  The bug was fixed for firefox50 but for firefox49 it was set to "wontfix"

Questions:
- Regarding the "flawed font" comment, is it possible to use a different theme or skin that doesn't use icomoon?
- The bug that was fixed per the thread, was that in Mozilla code base or is it firefox-specific? I'm not sure where the line between the two is drawn.  If it was applied to Mozilla then if Komodo uses same code base as firefox50 or later, it seems this might be a different though related issue.  If it uses the same as firefox49 or older version then seems like we have a pretty good idea of the issue.
- Did testers try to repro the problem on a machine that has HW acceleration turned off?

FYI:
- I am looking into if acceleration is something I can 'add' as it does not appear my current drivers support acceleration.  I'm getting a warning when attempting to install updated intel drivers saying it will conflict with the current configuration.  Will sort that out with IT.

**Comment by cgchoffman** [comment]
@nhtmo, I've found another resource where a user resolved this by [setting two more configs](https://support.mozilla.org/en-US/questions/1127796):
```
- gfx.direct2d.force-enabled -> True
- gfx.font_rendering.cleartype.always_use_for_content -> True
- gfx.font_rendering.directwrite.force-enabled -> True
```
Going to answer some of your question and comments:
- Komodo is built on Mozilla (firefox) 35
- **Regarding the "flawed font" comment, is it possible to use a different theme or skin that doesn't use icomoon?** This isn't possible. 
- **The bug that was fixed per the thread, was that in Mozilla code base or is it firefox-specific?** For all intents and purposes Firefox and the Mozilla framework are synonymous.
-**Did testers try to repro the problem on a machine that has HW acceleration turned off?** @i-shenl did you try that?
- Re: HW Acceleration:  Could you try the first item in this troubleshooting section: http://docs.komodoide.com/Troubleshooting/Komodo-has-weird-graphical-artifacts.  I believe you've done the `XRE` suggestion already.

**Comment by nhtmo** [comment]
Steps taken:
- set gfx.font_rendering.cleartype.always_use_for_content to True
- searched for gfx.font_rendering.directwrite.force-enabled but could not find
- restarted Komodo, problem persists
- found gfx.font_rendering.directwrite.enabled (close to one specified) and for kicks set that to true
- restarted Komodo, IT WORKS!!!!!

THANK YOU!!! We're back in business...

So, it appears that this combination works for me (only slight variation):
- gfx.direct2d.force-enabled -> True
- gfx.font_rendering.cleartype.always_use_for_content -> True
- gfx.font_rendering.directwrite.enabled -> True

Well done!  Thanks again!

**Comment by cgchoffman** [comment]
> found gfx.font_rendering.directwrite.enabled (close to one specified) and for kicks set that to true

nice digging @nhtmo! Glad we finally got you sorted!  I'm going to close this issue for now as you're the only user that has hit it.  If the issue becomes more common we can looking to back porting the fix from Mozilla.
