### ISSUE TITLE
Console: History: can't use arrow keys to move cursor

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#702]
- Open the console
- Type a command and press enter
- Press up
- Previous command appears
- Expect: To be able to move cursor using arrow keys through text to change a portion of the command
- Actual: Can't only delete

**Comment by Naatan** [comment]
Works fine for me. Are you on nightly or master? I did fix something related to this a few days ago.

**Comment by cgchoffman** [comment]
I think it was my master.  I'll check now....ish

**Comment by cgchoffman** [comment]
Master.  Changing description and title to reflect slight difference..

**Comment by Naatan** [comment]
That's the bug I fixed.. hopefully not something Windows specific. Can you double check you are up to date?

**Comment by cgchoffman** [comment]
Checking

**Comment by cgchoffman** [comment]
Haven't been able to build Komodo since distclean.  working around that.

**Comment by cgchoffman** [comment]
Still can't move left or right using arrow keys or End and Home even after distclean.

**Comment by Naatan** [comment]
End and Home seem to not work for me either, but arrow keys work on Windows. Will look into home/end and hopefully that will also fix arrow keys for you.

**Comment by cgchoffman** [comment]
I'll have to check a nightly I guess.  Arrow keys don't work at all.

**Comment by Naatan** [comment]
Gonna have to implement the input using a textarea and something like this: http://stackoverflow.com/a/14876014/490321

As unfortunately contenteditable seems to be hopelessly broken on our version of Mozilla under Windows.

Shouldn't be too much work, but still sucks.
