### ISSUE TITLE
Issue with Search In Folder/Project on Mac OS X Yosemite (10.10.4)

### ISSUE THREAD

**Issue by adzchappers** [Komodo/KomodoEdit#984]
Having an issue with Search in folder/Project. I can't even find the search in project selection anymore, and when trying to search in a folder, it won't select a folder, them when you hit the find button it won't run the search. Occasionally it'll then open a new window and you'll find half a dozen searches in there that have all failed, occasionally I get another error popup.

![screen shot 2016-01-05 at 14 40 43](https://cloud.githubusercontent.com/assets/611127/12117709/6f9e939a-b3ba-11e5-8a2a-c6eaa39c33aa.png)
![screen shot 2016-01-05 at 14 41 35](https://cloud.githubusercontent.com/assets/611127/12117708/6f9e25ae-b3ba-11e5-8b22-955aedb1f0c1.png)

**Comment by cgchoffman** [comment]
What version of komodo?  Komodo menu > About Komodo.

**Comment by adzchappers** [comment]
Komodo Edit, version 9.3.2, build 16460, platform macosx. Built on Thu Dec 10 19:37:46 2015.

Made sure I got the OS version, completely forgot about the damned program version!

**Comment by Naatan** [comment]
Do you have multiple windows open? 

This exact issue was fixed in 9.3.2, are you sure you didn't update in between having this issue and checking your version?

**Comment by adzchappers** [comment]
I have multiple Komodo Edit windows open, as I'm working on multiple projects.

I'm having the issue today still, and definitely working on 9.3.2

**Comment by Naatan** [comment]
Could you please try reproducing the issue with only one window open?

**Comment by adzchappers** [comment]
I have closed the rest of my open windows, so I'm down to one open window. I still don't have the Project option in where to search, can't modify the search in files option either. When I do try to click on a folder and say search - it resets the WHERE from files to current document. Find All not do anything.


I completely closed all instances of Komodo Edit and opened up a fresh instance. I have the option for Project back, Find all in projects appears to be working. I have now tried to search in Files, and chose a folder, but I then get this message: No files were found to search in. - Yes there were files in that folder.

**Comment by Naatan** [comment]
To clarify; when you restarted Komodo did you restart it with only a single window?

**Comment by adzchappers** [comment]
Yes, restarted and made sure that only a single window opened.

**Comment by Naatan** [comment]
Can you reproduce this when starting in safe mode? Help > Troubleshooting > Restart in Safe-Mode.

**Comment by adzchappers** [comment]
Search in files seems to be working in safe mode.

and so does having multiple windows open searching their own folders.

**Comment by Naatan** [comment]
Interesting. Could you try restarting again and then trying `Help > Troubleshooting > Restart Without Addons`.

If the problem persists after that, please share your error log (after reproducing the issue) - Help > Troubleshooting > View Log File.

**Comment by adzchappers** [comment]
Hmmm, I haven't got any addons installed...

I've tried restarting without addons, search in project is working, but I can't search in Files.

I have now restarted normally, and reproduced the search in files error, opened another window and then duplicated the search in files error, here is my log file.

[2016-01-06 17:24:13,786] [INFO] Startup: Welcome to Komodo Edit 9.3.2 build 16460 (platform macosx, running on Darwin 14.4.0 version Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64)
[2016-01-06 17:24:13,786] [INFO] Startup: /Applications/Komodo Edit 9.app/Contents/MacOS/komodo built on Thu Dec 10 19:37:46 2015
[2016-01-06 17:24:13,791] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2016-01-06 17:24:14,117] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-01-06 17:24:14,155] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2016-01-06 17:24:14,259] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2669
[2016-01-06 17:24:14,277] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2669
[2016-01-06 17:24:14,551] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-01-06 17:24:14,608] [WARNING] keybindings: [Meta+Shift+Down] was used for 'cmd_selectDocumentHome', overriding to use 'cmd_selectDocumentEnd'
[2016-01-06 17:24:14,981] [ERROR] koScintillaSchemeService: Scheme Atelierdune_Dark is not writeable
[2016-01-06 17:24:14,981] [WARNING] koScintillaSchemeService: Upgraded scheme u'Atelierdune_Dark' from version 14 to 15.
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:24:15,378] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:24:15,379] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:24:15,474] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:24:15,474] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:24:15,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:24:15,558] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:24:15,559] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:24:15,560] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:24:17,138] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:24:17,138] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:24:17,139] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:24:17,952] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/components/koamAddonManager.js:138
[2016-01-06 17:24:18,815] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-01-06 17:26:17,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:26:17,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:26:17,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:26:17,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:26:17,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:26:17,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:26:17,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:26:17,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:03,493] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2016-01-06 17:27:03,628] [WARNING] keybindings: [Meta+Shift+Down] was used for 'cmd_selectDocumentHome', overriding to use 'cmd_selectDocumentEnd'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:04,210] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:04,211] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:04,211] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:04,706] [WARNING] views: Inconsistent view count in view_closed event
[2016-01-06 17:27:04,742] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:04,743] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:04,744] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:04,792] [WARNING] views: Inconsistent view count in view_opened event
[2016-01-06 17:27:04,886] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:04,886] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:04,886] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:04,887] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:04,887] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:04,887] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:04,887] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:04,887] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,071] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,071] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,072] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,207] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,208] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,209] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,310] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,419] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,419] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,545] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,545] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,546] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,656] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,657] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,776] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,777] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,889] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,889] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,890] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:05,997] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:05,997] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:05,998] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,124] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,125] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,126] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,241] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,354] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,357] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,358] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,358] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,358] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,358] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,358] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,359] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,470] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,470] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,470] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,470] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,470] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,471] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,471] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,471] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,595] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,595] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,596] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:06,731] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:06,731] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:06,732] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-01-06 17:27:07,378] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-01-06 17:27:07,639] [ERROR] commands: An error occurred executing the cmd_findInFiles command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "_findBrowser.contentWindow.on_load is not a function" {file: "chrome://komodo/content/launch.js" line: 218}]'[JavaScript Error: "_findBrowser.contentWindow.on_load is not a function" {file: "chrome://komodo/content/launch.js" line: 218}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "_findBrowser.contentWindow.on_load is not a function" {file: "chrome://komodo/co'...306 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 215
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-01-06 17:27:07,647] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2016-01-06 17:27:08,682] [WARNING] console-logger: Trying to re-register CID '{16265b4a-4323-4250-8ef1-b4f4ee859136}' already registered by file:///Applications/Komodo%20Edit%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/koScopeFiles.py. (1) in file:///Applications/Komodo%20Edit%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:1
[2016-01-06 17:27:08,684] [ERROR] console-logger: TypeError: _findBrowser.contentWindow.on_load is not a function (2) in chrome://komodo/content/launch.js:218
Traceback (most recent call last):
  File "chrome://komodo/content/launch.js", line 218, in 

[2016-01-06 17:27:09,708] [WARNING] codeintel.css: Unable to process CSS selector '[class^="icon-"], [class*=" icon-"]'
[2016-01-06 17:27:27,495] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-01-06 17:27:27,495] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-01-06 17:27:27,496] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'

**Comment by Naatan** [comment]
Could you try `Help > Troubleshooting > Reset UI Setup`?

**Comment by adzchappers** [comment]
Tried, still getting the No Files were found to search in.

**Comment by Naatan** [comment]
Are there any substantial differences between a clean startup (safe mode) and your personal setup?

**Comment by adzchappers** [comment]
It was a brand new fresh install as I stopped using Komodo Edit because of a gui issue with the last version, but have come back to it because I missed it!

**Comment by Naatan** [comment]
ok, if you don't mind could you zip up your [profile folder](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data) and send it to support@activestate.com with a reference to this issue? Then do a full profile reset: `Help > Troubleshooting > Reset Everything`.

**Comment by adzchappers** [comment]
Will do this tomorrow as I've left the office now. Thanks for your help.

**Comment by adzchappers** [comment]
Still getting this issue, and looking to zip the folder up, but it's 75MB when zipped. Is this right?

**Comment by Naatan** [comment]
You can delete the codeintel folder to make it a bit smaller.

**Comment by adzchappers** [comment]
Removed all komodo files from ~/Library and sub folders, uninstalled and reinstalled and searching seems to have fixed itself.
